---
name: Anchore SBOM
description: Anchore SBOM
inputs:
  image:
    description: Image
    required: false
  timeout:
    description: Timeout
    required: false
    default: "60"
runs:
  using: composite
  steps:
    - name: Analysis
      id: scan-sbom
      uses: anchore/scan-action@v3
      with:
        image: ${{ inputs.image != null && inputs.image || null }}
        fail-build: false
        # severity-cutoff: medium
    - name: Anchore - Upload SBOM scan SARIF report
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan-sbom.outputs.sarif }}
