---
name: MegaLinter
description: MegaLinter
inputs:
  timeout:
    description: Timeout
    required: false
    default: "60"
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ github.event_name == 'push' && 1 || 0 }}
    - name: Analysis
      uses: oxsecurity/megalinter@v7
      env:
        VALIDATE_ALL_CODEBASE: ${{ contains(github.event_name, 'push') }}
        GITHUB_TOKEN: ${{ github.token }}
    - name: Archive production artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: MegaLinter
        path: |
          megalinter-reports
          mega-linter.log
