---
name: Anchore SBOM
description: Anchore SBOM
inputs:
  sonar_host_url:
    description: SonarQube URL
    required: false
    # default: ${{ vars.sonar_host_url }}
  sonar_token:
    description: SonarQube Token
    required: false
    # default: ${{ secrets.sonar_token }}
  sonar_project_key:
    description: SonarQube Project key
    required: false
    default: ${{ github.event.repository.name }}
  timeout:
    description: Timeout
    required: false
    default: "60"
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Analysis
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        sonar_host_url: ${{ inputs.sonar_host_url }}
        sonar_token: ${{ inputs.sonar_token }}
      with:
        args: -D sonar.projectKey=${{ inputs.sonar_project_key }}
    - name: Analysis Check
      uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
      env:
        sonar_host_url: ${{ inputs.sonar_host_url }}
        sonar_token: ${{ inputs.sonar_token }}
