---
name: Anchore SBOM
description: Continuous vulnerability scanning
inputs:
  image:
    description: Image
    required: false
runs:
  using: composite
  steps:
    - name: Analysis
      id: grype-scan
      uses: anchore/scan-action@v3
      with:
        image: ${{ inputs.image }}
        fail-build: false
        # severity-cutoff: medium
    - name: Upload SBOM scan SARIF report
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.grype-scan.outputs.sarif }}
    # TODO: Add label feature for QG
