---
name: DEV - Use reusable workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test_choice_node:
    name: Choice Node builder
    uses: mxbp/github-pipelines/.github/workflows/node.yml@develop
    with:
      version: 18
      build_command: npm run build
  test_choice_go:
    name: Choice Go builder
    uses: ./.github/workflows/choice_workflow_builder.yml
    with:
      go_version: 1.21.4
  test_1:
    name: Use reusable job - default
    uses: ./.github/workflows/reusable_workflow_environment.yml
    with:
      inputs_url: http://www.example.com/default
      matrix_string: qwe
  test_2:
    name: Use reusable job - DEV
    # needs: test_1
    uses: ./.github/workflows/reusable_workflow_environment.yml
    with:
      inputs_environment: dev
      inputs_url: http://dev.example.com/dev
      matrix_string: rty, fgh, vbn
  pr:
    name: PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: PR
      run: |
        echo "head_ref: --branch=${{ github.head_ref }}"
        echo "number: --merge-id=${{ github.event.number }}"
        echo "- - - - ${{ github.event_name }} - - - -"
        echo "ref_name: --branch=${{ github.ref_name }}"
  push:
    name: Push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Push
      run: |
        echo "ref_name: --branch=${{ github.ref_name }}"
        echo "- - - - ${{ github.event_name }} - - - -"
        echo "head_ref: --branch=${{ github.head_ref }}"
        echo "number: --merge-id=${{ github.event.number }}"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Test / ${{ github.event_name == 'pull_request' && 'Build' || 'Build and Push' }}
      run: >
        echo "${{ github.event_name == 'pull_request' &&
        format('--branch={0} --merge-id={1}', github.head_ref, github.event.number) ||
        format('--branch={0}', github.ref_name) }}"
        echo "- - - - ${{ github.event_name }} - - - -"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use composite actions
      uses: ./.github/workflows/actions.yml

    # - name: Checkout branch
    #   uses: actions/checkout@v3
    # - name: Update Artifact Version
    #   run: |
    #     git config user.name "GitHub Actions Bot"
    #     git config user.email "<>"
    #     echo "${{ github.sha }}" > development-version.txt
    #     git add development-version.txt
    #     git commit -m "update development version: ${{ github.sha }}"
    #     git pull --rebase
    #     git push
...
