---
name: Quality Gates
on:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
      # NOTE: SonarQube
      sonar_host_url:
        required: false
        type: string
      sonar_token:
        required: false
        type: string
      sonar_project_key:
        required: false
        type: string
      # NOTE: CodeQL
      codeql_language:
        required: false
        type: string
      # NOTE: GitHub Actions
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      timeout:
        required: false
        type: number
        default: 60
    secrets:
      sonar_token:
        required: false
jobs:
  linter:
    name: MegaLinter
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    continue-on-error: true
    timeout-minutes: ${{ inputs.timeout }}
    # FIXME: Remove
    env: # Comment env block if you don't want to apply fixes
      # Apply linter fixes configuration
      APPLY_FIXES: all # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)
      APPLY_FIXES_EVENT: pull_request # Decide which event triggers application of fixes in a commit or a PR (pull_request, push, all)
      APPLY_FIXES_MODE: commit # If APPLY_FIXES is used, defines if the fixes are directly committed (commit) or posted in a PR (pull_request)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: mxbp/github-pipelines/actions/quality-gates-linter@main
  sbom:
    name: Anchore SBOM
    runs-on: ${{ inputs.runs-on }}
    permissions:
      actions: read
      contents: read
      # issues: write # FIXME: Remove
      # pull-requests: write # FIXME: Remove
      security-events: write
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Download source artifact
        if: ${{ inputs.build == 'true' }}
        uses: actions/download-artifact@v4
        with:
          name: app-source-${{ github.run_number }}
          path: ${{ github.workspace }}
      - name: Checkout
        if: ${{ inputs.build == 'false' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: mxbp/github-pipelines/actions/quality-gates-anchore@main
  sonarqube:
    name: Sonarqube
    runs-on: ${{ inputs.runs-on }}
    if: ${{ inputs.sonar_token == 'true' && inputs.sonar_host_url != '' && inputs.sonar_project_key != '' }}
    # permissions:
    #   pull-requests: write
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Download source artifact
        if: ${{ inputs.build == 'true' }}
        uses: actions/download-artifact@v4
        with:
          name: app-source-${{ github.run_number }}
          path: ${{ github.workspace }}
      - name: Checkout
        if: ${{ inputs.build == 'false' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: mxbp/github-pipelines/actions/quality-gates-sonarqube@main
        with:
          sonar_host_url: ${{ inputs.sonar_host_url }}
          sonar_token: ${{ secrets.sonar_token }}
          sonar_project_key: ${{ inputs.sonar_project_key}}
  codeql:
    name: CodeQL
    runs-on: ${{ inputs.runs-on }}
    if: ${{ inputs.codeql_language != '' && inputs.build == 'true' }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        # TODO: Add auto detect language
        # https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-languages
        language: ${{ fromJson(inputs.codeql_language) }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Download source artifact
        if: ${{ inputs.build == 'true' }}
        uses: actions/download-artifact@v4
        with:
          name: app-source-${{ github.run_number }}
          path: ${{ github.workspace }}
      - name: Checkout
        if: ${{ inputs.build == 'false' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: mxbp/github-pipelines/actions/quality-gates-codeql@main
        with:
          language: ${{ matrix.language }}
