---
name: Reusable workflow

on:
  workflow_call:
    inputs:
      inputs_test_1:
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      inputs_test_2:
        required: false
        type: string
      inputs_test_3:
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      inputs_test_4:
        required: false
        type: string
    secrets:
      secrets_test_1:
        required: false
      secrets_test_2:
        required: false

jobs:
  test_inputs_1_2:
    name: Echo Inputs 1, 2
    runs-on: ubuntu-latest
    steps:
    - name: Echo inputs 1
      run: |
        echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
        echo "inputs - ${{ inputs.inputs_test_1 }}"
      # Result: "inputs - Hello reusable workflow!"
    - name: Echo inputs 2
      run: |
        echo "inputs - ${{ inputs.inputs_test_2 != null && inputs.inputs_test_2 || 'Inputs is Null' }}"
      # Result: "inputs - Hello reusable workflow!"

  test_inputs_3_4:
    name: Echo Inputs 3, 4
    runs-on: ubuntu-latest
    if: inputs.inputs_test_4 != null
    steps:
    - name: Echo inputs 3
      run: |
        echo "inputs - ${{ inputs.inputs_test_3 }}"
      # Result: "inputs - github_pipelines"
    - name: Echo inputs 4
      run: |
        echo "inputs - ${{ inputs.inputs_test_4 != null && inputs.inputs_test_4 || 'Inputs is Null' }}"
      # Result: "inputs - Inputs is Null"

  test_secrets_1:
    name: Echo Secrets 1
    runs-on: ubuntu-latest
    steps:
    - name: Echo secrets 1
      run: |
        echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "secrets - ${{ secrets.secrets_test_1 != null && secrets.secrets_test_1 || 'Secret is Null' }}"
      # Result: "secrets - ***"

  test_secrets_2:
    name: Echo Secrets 2
    runs-on: ubuntu-latest
    steps:
    - name: Echo secrets 2
      run: |
        echo "secrets - ${{ secrets.secrets_test_2 != null && secrets.secrets_test_2 || 'Secret is Null' }}"
      # Result: "secrets - Secret is Null"
...
